version: "3.8"
services:

  collector:
    build:
      context: .
    network_mode: "host"
    volumes:
    - type: bind
      source: /proc/net/arp
      target: /proc/net/arp
      read_only: true
    ports:
    - "8080:8000"
    privileged: true
