version: "3.8"
services:
  api:
    build:
      context: ./api
    networks:
      - backend
    volumes:
      - "./api:/srv/http/api"
    environment:
      - APIURL=http://collector:8000
    restart: always
    depends_on:
      - collector
    ports:
      - "80:5000"

  collector:
    build:
      context: ./collector
      network: host
    volumes:
      - "./collector:/srv/http/collector"
    networks:
      - backend
    ports:
      - "8080:8000"

networks:
  backend:
    driver: bridge
