version: "3.8"
services:
  api:
    build:
      context: ./api
    networks:
      - backend
    volumes:
    - "./api:/srv/http/api"
    restart: always
    depends_on:
      - collector
    ports:
    - "80:5000"

  collector:
    build:
      context: ./collector
    volumes:
    - "./collector:/srv/http/collector"
    networks:
      - backend
    network_mode: "host"

networks:
  backend:
    driver: bridge
