# Generated by Django 3.1.3 on 2020-11-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255, verbose_name='Device name')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('mac_address', models.CharField(max_length=255, verbose_name='MAC Address')),
            ],
        ),
    ]
